# Generated by Django 6.1 on 2026-08-30 06:50

import django.utils.timezone
import django_cryptography.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('email_encrypted', django_cryptography.fields.encrypt(models.EmailField(blank=True, max_length=254, null=True))),
                ('email_hash', models.CharField(blank=True, max_length=64, null=True, unique=True)),
                ('wallet_number', models.CharField(editable=False, max_length=15, unique=True)),
                ('phone_number_encrypted', django_cryptography.fields.encrypt(models.CharField(max_length=11))),
                ('phone_number_hash', models.CharField(max_length=64, unique=True, verbose_name='phone number')),
                ('user_type', models.CharField(choices=[('customer', 'Customer'), ('agent', 'Agent'), ('merchant', 'Merchant')], default='customer', max_length=10)),
                ('phone_number', models.CharField(max_length=11, unique=True)),
                ('national_id_encrypted', django_cryptography.fields.encrypt(models.CharField(blank=True, max_length=24, null=True))),
                ('national_id_hash', models.CharField(blank=True, max_length=64, null=True, unique=True)),
                ('address_encrypted', django_cryptography.fields.encrypt(models.TextField(blank=True, null=True))),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('is_phone_verified', models.BooleanField(default=False)),
                ('is_kyc_verified', models.BooleanField(default=False)),
                ('kyc_approved_at', models.DateTimeField(blank=True, null=True)),
                ('failed_pin_attempts', models.PositiveSmallIntegerField(default=0)),
                ('is_locked', models.BooleanField(default=False)),
                ('locked_until', models.DateTimeField(blank=True, null=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='OTP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.CharField(max_length=11)),
                ('code_hash', models.CharField(max_length=64)),
                ('purpose', models.CharField(choices=[('registration', 'Registration'), ('login', 'Login'), ('password_reset', 'Password Reset')], default='registration', max_length=20)),
                ('attempts', models.PositiveSmallIntegerField(default=0)),
                ('is_used', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField()),
            ],
            options={
                'indexes': [models.Index(fields=['phone_number', 'purpose'], name='accounts_ot_phone_n_3b8ec0_idx')],
            },
        ),
    ]
