# Generated by Django 6.1 on 2026-09-03 03:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_customeridallocation'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='otp',
            name='accounts_ot_phone_n_3b8ec0_idx',
        ),
        migrations.AddField(
            model_name='otp',
            name='phone_hash',
            field=models.CharField(default='', max_length=64),
            preserve_default=False,
        ),
        migrations.AddIndex(
            model_name='otp',
            index=models.Index(fields=['phone_hash', 'purpose'], name='accounts_ot_phone_h_7d6b6d_idx'),
        ),
        migrations.RemoveField(
            model_name='otp',
            name='phone_number',
        ),
    ]
