# Generated by Django 6.1 on 2026-09-06 06:24

import django.db.models.deletion
import django.db.models.expressions
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('type', models.CharField(choices=[('p2p_transfer', 'P2P Transfer')], max_length=20)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=10)),
                ('idempotency_key', models.CharField(blank=True, max_length=64, null=True, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='WalletTier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=32, unique=True)),
                ('name', models.CharField(max_length=64)),
                ('max_balance', models.DecimalField(decimal_places=2, max_digits=19)),
                ('daily_credit_limit', models.DecimalField(decimal_places=2, max_digits=19)),
                ('daily_debit_limit', models.DecimalField(decimal_places=2, max_digits=19)),
                ('monthly_credit_limit', models.DecimalField(decimal_places=2, max_digits=19)),
                ('monthly_debit_limit', models.DecimalField(decimal_places=2, max_digits=19)),
                ('daily_txn_count_limit', models.PositiveIntegerField()),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='Wallet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wallet_type', models.CharField(choices=[('primary', 'Primary'), ('agent_float', 'Agent float'), ('agent_commission', 'Agent commission'), ('merchant_settlement', 'Merchant settlement')], default='primary', max_length=20)),
                ('account_number', models.CharField(editable=False, max_length=20, unique=True)),
                ('currency', models.CharField(default='BDT', max_length=3)),
                ('balance', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=19)),
                ('reserved', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=19)),
                ('overdraft_limit', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=19)),
                ('status', models.CharField(choices=[('pending', 'Pending activation'), ('active', 'Active'), ('dormant', 'Dormant'), ('frozen', 'Frozen'), ('suspended', 'Suspended'), ('closed', 'Closed')], default='pending', max_length=12)),
                ('status_reason', models.CharField(blank=True, default='', max_length=255)),
                ('status_changed_at', models.DateTimeField(blank=True, null=True)),
                ('activated_at', models.DateTimeField(blank=True, null=True)),
                ('closed_at', models.DateTimeField(blank=True, null=True)),
                ('last_activity_at', models.DateTimeField(blank=True, null=True)),
                ('version', models.PositiveBigIntegerField(default=0)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='wallets', to=settings.AUTH_USER_MODEL)),
                ('tier', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='wallets', to='wallet.wallettier')),
            ],
        ),
        migrations.CreateModel(
            name='LedgerEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=14)),
                ('direction', models.CharField(choices=[('debit', 'Debit'), ('credit', 'Credit')], max_length=6)),
                ('balance_after', models.DecimalField(decimal_places=2, max_digits=14)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('transaction', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='entries', to='wallet.transaction')),
                ('wallet', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='entries', to='wallet.wallet')),
            ],
            options={
                'indexes': [models.Index(fields=['wallet', '-created_at'], name='wallet_ledg_wallet__463b44_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(('amount__gt', 0)), name='ledgerentry_amount_positive')],
            },
        ),
        migrations.AddIndex(
            model_name='wallet',
            index=models.Index(fields=['status'], name='wallet_wall_status_7f7e68_idx'),
        ),
        migrations.AddIndex(
            model_name='wallet',
            index=models.Index(fields=['last_activity_at'], name='wallet_wall_last_ac_119b04_idx'),
        ),
        migrations.AddConstraint(
            model_name='wallet',
            constraint=models.UniqueConstraint(fields=('customer', 'wallet_type'), name='uniq_customer_wallet_type'),
        ),
        migrations.AddConstraint(
            model_name='wallet',
            constraint=models.CheckConstraint(condition=models.Q(('reserved__gte', 0)), name='wallet_reserved_non_negative'),
        ),
        migrations.AddConstraint(
            model_name='wallet',
            constraint=models.CheckConstraint(condition=models.Q(('balance__gte', django.db.models.expressions.CombinedExpression(models.F('overdraft_limit'), '*', models.Value(-1)))), name='wallet_balance_within_overdraft'),
        ),
        migrations.AddConstraint(
            model_name='wallet',
            constraint=models.CheckConstraint(condition=models.Q(('reserved__lte', django.db.models.expressions.CombinedExpression(models.F('balance'), '+', models.F('overdraft_limit')))), name='wallet_reserved_within_balance'),
        ),
    ]
