# Generated by Django 6.1 on 2026-09-07 09:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0002_seed_wallet_tiers'),
    ]

    operations = [
        migrations.RenameField(
            model_name='wallet',
            old_name='account_number',
            new_name='wallet_number',
        ),
    ]
