# Generated by Django 6.1 on 2026-09-07 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0003_rename_account_number_wallet_wallet_number'),
    ]

    operations = [
        migrations.CreateModel(
            name='TxnCounter',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'wallet_txn_counter',
            },
        ),
        migrations.AddField(
            model_name='transaction',
            name='reference',
            field=models.CharField(default='', editable=False, max_length=16, unique=True),
            preserve_default=False,
        ),
    ]
